mongodb:
  dsn: mongodb://root:example@localhost:27017/
  db_name: orderBooks
debug: true
RMQ_CONN_STR: amqp://guest:guest@localhost:8003/
RMQ_CHANNEL_NAME: order_book
REST_URL_BINANCE: https://api.binance.com/api/v3/depth
STREAM_URL_URL_BINANCE: wss://stream.binance.com:9443